### ISSUE TITLE
Recipes

### ISSUE THREAD

**Issue by Gaby-TM** [mcgrizzz/ProRecipes#14]
Is possible somehow to leave items in crafting grid after craft an item? For example, in vanilla recipe of cake, after you craft it, you get an empty bucket back, and i was wondering if it,s possible to do same thing but with different items.

**Comment by mcgrizzz** [comment]
Not currently possible with the normal recipes, but you can achieve a similar effect with multicraft recipes. 

I'll look into it, but due to the infrastructure that already exists, it may not be viable or even possible.
