### ISSUE TITLE
Spigot Watchdog Error

### ISSUE THREAD

**Issue by TheJayCool** [mcgrizzz/ProRecipes#2]
https://hastebin.com/aqipaxacef.md

I've been having this issue with the server for a while and it's makinf the server unresponsive about 5-10 minutes affer the server starts.

**Comment by TheJayCool** [comment]
https://pastebin.com/BBeAxnv5

The hastebin expired

**Comment by mcgrizzz** [comment]
This doesn't seem to be the latest version. Can you try the latest version and open a new ticket if there is the same issue ?
