### ISSUE TITLE
Update link goes to the old resource page

### ISSUE THREAD

**Issue by TrademarkTM** [mcgrizzz/ProRecipes#25]
The title says it all ^^
It's a goo.gl link which leads you to the old page.

**Comment by mcgrizzz** [comment]
I'm not sure which link you're referring to.

**Comment by TrademarkTM** [comment]
The one which tells you to update your plugin to the lastest version.

**Comment by mcgrizzz** [comment]
I will update that right now. Didn't even notice that. Thank you for letting me know.
