### ISSUE TITLE
[Bug] /Items only shows one Item under the material list

### ISSUE THREAD

**Issue by pinkpig3777** [mcgrizzz/ProRecipes#28]
As stated in the title, /Items only shows one item when it should show 24 under the material. Similarly, there should be multiple materials rather than just one (the stick).

/Items: https://gyazo.com/45f0f813fe16fee04815a5df7c0ca8c8
/Items -> Stick Material: https://gyazo.com/56964d531d300a7e34c92b931b281caf
/Recipes -> Shaped Recipes: https://gyazo.com/5a265e69018b50f6a576d59bb638e413

Server Version: https://gyazo.com/3bc5b918e61750a2a9cf8d2c04f922f8
Plugins: https://gyazo.com/dce7b9f7c3c1bc367ca6cb5ac8e36263
ProRecipes Plugin Version: 2.1.1
ProRecipes Config: Unchanged. Did not modify.

Thanks!

**Comment by pinkpig3777** [comment]
Note: It needed a server restart to fix it.

**Comment by mcgrizzz** [comment]
Items in the /items command are calculated on server startup to save on the resources required. This is not a bug, but a decided function.
