### ISSUE TITLE
 hello friend sorry i do not know much english

### ISSUE THREAD

**Issue by DolanBandolero** [mcgrizzz/ProRecipes#5]
I donated for your plugin since I am in a rpg project and your plugin was the most suitable.

what I wanted to say apart from updating to 1.12.2

that allows through a chest gui or aniatedmenu

create a 5x5 crafting table or 6x6. :/ sorry for my bad english.

you have a good day

**Comment by mcgrizzz** [comment]
I am releasing a newer version right now for 1.12.2. 

At the moment, I do not intend to add 5x5 or 6x6 crafting.
