### ISSUE TITLE
Error in console with shapeless recipe

### ISSUE THREAD

**Issue by VoxPopuliZombiemold** [mcgrizzz/ProRecipes#6]
I posted this on the forum thread before I saw the links on where to post issues, so I am posting here instead:

Getting this error with a shapeless recipe: https://hastebin.com/adefeqowol.md

I am using one of the most recent (if not the most recent as of this posting) paper spigot version, mc 1.12.2.

**Comment by mcgrizzz** [comment]
This is a deprecation error thrown by massivecraft. Please ignore, I cannot update at the moment without losing backwards compatibility. The plugin should function properly.
